#!/usr/bin/env python3

import re
import sys
from pathlib import Path


def parse_packed_rows(text: str):
    m = re.search(
        r"(?:static\s+)?const\s+\w+\s+traj_raw_packed\s*\[[^\]]+\]\s*\[[^\]]+\]\s*=\s*\{(.*)\};",
        text,
        re.DOTALL,
    )
    if not m:
        raise ValueError("Could not find traj_raw_packed[rows][cols] = { ... };")
    body = m.group(1)

    rows = []
    for row_txt in re.findall(r"\{([^{}]+)\}", body):
        nums = re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", row_txt)
        vals = [float(v) for v in nums]
        if len(vals) != 16:
            raise ValueError(f"Found row with {len(vals)} values, expected 16.")
        rows.append(vals)

    return rows


def fmt_row(vals):
    return "{" + ",".join(f"{v:.4f}" for v in vals) + "},"


def main():
    # if len(sys.argv) != 3:
    #     print("Usage: make_traj_header.py <input.h> <output.h>")
    #     sys.exit(1)

    input_path =  Path("/home/andrea/tinympc-crazyflie/trajectory_fpga.h") #Path(sys.argv[1])
    output_path = Path("/home/andrea/tinympc-crazyflie/apps/controller_tinympc_eigen/src/traj_fpga_100hz.h") # Path(sys.argv[2])

    packed = parse_packed_rows(input_path.read_text())

    x_rows = [r[:12] for r in packed]
    u_rows = [r[12:] for r in packed]

    # 50 Hz -> 100 Hz by duplicating each sample once.
    x_out = [r for r in x_rows] # for row in (r, r, r, r, r, r, r, r, r, r)]
    u_out = [r for r in u_rows] # for row in (r, r, r, r, r, r, r, r, r, r)]
    u_out = u_out[: len(x_out) - 1]

    lines = []
    lines.append("// Auto-generated by make_traj_header.py")
    lines.append(f"// Source: {input_path}")
    lines.append("")
    lines.append(f"static const float X_ref_data[{len(x_out)}][12] = {{")
    lines.extend(fmt_row(r) for r in x_out)
    lines.append("};")
    lines.append("")
    lines.append(f"static const float U_ref_data[{len(u_out)}][4] = {{")
    lines.extend(fmt_row(r) for r in u_out)
    lines.append("};")
    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))

    print(f"Wrote {output_path}")
    print(f"X_ref_data: {len(x_out)} rows")
    print(f"U_ref_data: {len(u_out)} rows")


if __name__ == "__main__":
    main()
